version: '3'
services:
  app:
    image: 919446158824.dkr.ecr.us-east-1.amazonaws.com/repoflow-container-server:linked
    ports:
     - "${SERVICE_PORT}:${SERVICE_PORT}"
  graph:
    image: 919446158824.dkr.ecr.us-east-1.amazonaws.com/repoflow-container-graph:linked
    volumes:
     - /home/victor/nodeflow/workspace:/home/node/workspace
     - /home/victor/.gitconfig:/home/node/.gitconfig
     - /home/victor/.ssh:/home/node/.ssh
    environment:
     - REPOFLOW_WORKSPACE=/home/node/workspace
    ports:
     - "${SERVICE_PORT}:${SERVICE_PORT}"
