version: '3'
services:
  app:
    image: 919446158824.dkr.ecr.us-east-1.amazonaws.com/repoflow-container-server:link
    env_file:
     - .env
    environment:
     - SERVICE_PORT=5040
     - GRAPHQL_URL=http://container-dependencies.graph.com:4040/graphql
     - EVENTS_URL=http://container-dependencies.graph.com:4040/events
    ports:
     - "5040:5040"
  graph:
    image: 919446158824.dkr.ecr.us-east-1.amazonaws.com/repoflow-container-graph:link
    env_file:
     - .env
    volumes:
     - /home/victor/nodeflow/workspace:/home/node/workspace
     - /home/victor/.gitconfig:/home/node/.gitconfig
     - /home/victor/.ssh:/home/node/.ssh
    environment:
     - SERVICE_PORT=4040
     - REPOFLOW_WORKSPACE=/home/node/workspace
    ports:
     - "4040:4040"
