version: '3'
services:
  web:
    image: repoflow/repoflow-container-server:1.70.2-master
    volumes:
     - ~/nodeflow/workspace:/home/node/workspace
    environment:
     - REPOFLOW_WEB_SERVICE_HOST=web.repoflow.local
     - REPOFLOW_WEB_SERVICE_PORT=5050
     - REPOFLOW_WORKSPACE=/home/node/workspace
     - REPOFLOW_GRAPH_URL=http://graph.repoflow.local:4050/graphql
     - REPOFLOW_EVENTS_URL=http://graph.repoflow.local:4050/events
    hostname: web.repoflow.local
    ports:
     - 5050:5050
    networks:
      network-repoflow: {aliases: [web.repoflow.local]}
    extra_hosts:
        - 'localbuild:${DOCKERHOST}'
  graph:
    image: repoflow/repoflow-container-graph:1.70.2-master
    volumes:
     - ~/nodeflow/workspace:/home/node/workspace
     - ~/.gitconfig:/home/node/.gitconfig
     - ~/.ssh:/home/node/.ssh
    environment:
     - REPOFLOW_GRAPH_SERVICE_HOST=graph.repoflow.local
     - REPOFLOW_GRAPH_SERVICE_PORT=4050
     - REPOFLOW_WORKSPACE=/home/node/workspace
    hostname: graph.repoflow.local
    ports:
     - 4050:4050
    networks:
      network-repoflow: {aliases: [graph.repoflow.local]}
networks:
  network-repoflow:
    external: true
