version: '3'
services:
  app:
    image: 919446158824.dkr.ecr.us-east-1.amazonaws.com/repoflow-container-server:1.70.0-master
    volumes:
     - ~/nodeflow/workspace:/home/node/workspace
    environment:
     - SERVICE_HOST=app.repoflow.local
     - SERVICE_PORT=5060
     - REPOFLOW_WORKSPACE=/home/node/workspace
     - GRAPHQL_URL=http://graph.repoflow.local:4050/graphql
     - EVENTS_URL=http://graph.repoflow.local:4050/events
    hostname: app.repoflow.local
    ports:
     - 5060:5060
    networks:
      network-repoflow: {aliases: [app.repoflow.local]}
    extra_hosts:
        - 'localbuild:${DOCKERHOST}'
  graph:
    image: 919446158824.dkr.ecr.us-east-1.amazonaws.com/repoflow-container-graph:1.70.0-master
    volumes:
     - ~/nodeflow/workspace:/home/node/workspace
     - ~/.gitconfig:/home/node/.gitconfig
     - ~/.ssh:/home/node/.ssh
    environment:
     - SERVICE_HOST=graph.repoflow.local
     - SERVICE_PORT=4050
     - REPOFLOW_WORKSPACE=/home/node/workspace
    hostname: graph.repoflow.local
    ports:
     - 4050:4050
    networks:
      network-repoflow: {aliases: [graph.repoflow.local]}
    extra_hosts:
        - 'localbuild:${DOCKERHOST}'
networks:
  network-repoflow:
    external: true
